# Site settings
title: "Hello, is this thing on?"
email: james.abley@gmail.com
description: "Intermittent cake-hole flappings of a nerd"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jamesabley.com" # the base hostname & protocol for your site
twitter_username: jabley
github_username:  jabley

permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "James Abley"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

collections:
  talks:
    output: true
